CREATE DATABASE Acceloka
GO

USE Acceloka
GO

CREATE TABLE Category(
	Id INT NOT NULL
	CONSTRAINT PK_Category PRIMARY KEY IDENTITY,

	Name VARCHAR(255) NOT NULL,

	CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
	CreatedBy VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
	UpdatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
	UpdatedBy VARCHAR(255) NOT NULL DEFAULT 'SYSTEM'
);

CREATE TABLE Ticket(
	Code VARCHAR(50) NOT NULL
	CONSTRAINT PK_Ticket PRIMARY KEY,

	Name varchar(255) not null,
	Price INT NOT NULL,
	Quota INT NOT NULL,
	Date DATETIME NOT NULL,

	CategoryId INT NOT NULL 
	CONSTRAINT FK_Ticket_Category FOREIGN KEY REFERENCES Category(Id) ON DELETE CASCADE,

	CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
	CreatedBy VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
	UpdatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
	UpdatedBy VARCHAR(255) NOT NULL DEFAULT 'SYSTEM'
);

CREATE TABLE BookedTicket(
	Id INT NOT NULL
	CONSTRAINT PK_BookedTicket PRIMARY KEY IDENTITY,

	Date DATETIME NOT NULL,

	CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
	CreatedBy VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
	UpdatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
	UpdatedBy VARCHAR(255) NOT NULL DEFAULT 'SYSTEM'
);

CREATE TABLE Detail(
	Id INT NOT NULL
	CONSTRAINT PK_Detail PRIMARY KEY IDENTITY,

	Quantity INT NOT NULL,

	TicketCode VARCHAR(50) NOT NULL 
	CONSTRAINT FK_Detail_Ticket FOREIGN KEY REFERENCES Ticket(Code) ON DELETE CASCADE,

	BookedTicketId INT NOT NULL
	CONSTRAINT FK_Detail_BookedTicket FOREIGN KEY REFERENCES BookedTicket(Id) ON DELETE CASCADE,

	CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
	CreatedBy VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
	UpdatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
	UpdatedBy VARCHAR(255) NOT NULL DEFAULT 'SYSTEM'
);
